fn make_box(width) {
  length = width * 2;
  height = width + length;
  return Box(length, width, height);
}

box0 = make_box(2);

box = Box(10, 10, 10);
to_subtract = Box(5, 5, 5);
box_with_hole = difference(box, to_subtract);

l = [1, 2.5, "foo", box];
print(l);
